apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleipnir
  labels:
    app: sleipnir
spec:
  selector:
    matchLabels:
      app: sleipnir
  template:
    metadata:
      labels:
        app: sleipnir
    spec:
      containers:
        - name: sleipnir
          image: taemdev.azurecr.io/sleipnir:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
